### ISSUE TITLE
How to build this project in ubuntu?

### ISSUE THREAD

**Issue by lexuanquynh** [JohnSalazar/microservices-go-authentication#1]
Thanks for sharing this project.
How do I build this project for ubuntu server?

**Comment by JohnSalazar** [comment]
Hello, to compile this project for the Ubuntu server, access this
repository that contains the necessary information.
https://github.com/JohnSalazar/microservices-go-infra

Em sáb., 16 de dez. de 2023 às 11:40, Quynh ***@***.***>
escreveu:
